Repository codestates-seb/seb40_pre_018, pull requests merged in 2022-11, with the labels that each got.

#136 Update README.md
  README.md
Labels: documentation

#138 Feat: 답변 수정 페이지 추가
  client/src/App.js
  client/src/components/Content.js
  client/src/pages/Questions/EditAnswer.js
Labels: front, feat

#141 Fix: 메인페이지 리렌더링 문제
  client/src/components/Content.js
  client/src/components/Loading.js
  client/src/pages/Questions/AskQuestion.js
  client/src/pages/Questions/EditQuestion.js
  client/src/pages/Questions/QuestionDetail.js
  client/src/pages/Questions/QuestionList.js
  client/src/redux/renderSlice.js
  client/src/redux/store.js
Labels: bug, front, feat
